In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("./중고차데이터최종v2.csv", encoding="cp949")

In [5]:
df

,Unnamed: 0,index,이름,제조회사,모델명,세부모델,가격,배기량,연식,색상,...,신차가격,감가상각률,2023년(예상),2024년(예상),2025년(예상),2026년(예상),2027년(예상),2028년(예상),2029년(예상),2030년(예상)
0,0,0,쌍용 티볼리 LX 2WD 세부등급 없음,쌍용,티볼리,티볼리,1360,1597,2017,진주색,...,2050.0,7.9,1253.0,1154.0,1063.0,979.0,902.0,831.0,765.0,705.0
1,1,1,기아 올 뉴 모닝 럭셔리,기아,모닝,올 뉴 모닝 (11~15년),670,998,2012,진주색,...,1300.0,6.8,624.0,582.0,542.0,505.0,471.0,439.0,409.0,381.0
2,2,2,쉐보레(GM대우) 알페온 EL300 슈프림,쉐보레,알페온,알페온,900,2997,2012,은색,...,3600.0,8.3,825.0,757.0,694.0,636.0,583.0,535.0,491.0,450.0
3,3,3,쌍용 렉스턴 스포츠 디젤 2.2 4WD 노블레스,쌍용,렉스턴,렉스턴 스포츠 칸,2420,2157,2019,쥐색,...,3250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,4,쉐보레(GM대우) 더 뉴 말리부 1.3 터보 프리미어 세부등급없음,쉐보레,말리부,더 뉴 말리부,2240,1341,2021,검정색,...,3150.0,10.8,1998.0,1782.0,1590.0,1418.0,1265.0,1128.0,1006.0,897.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14552,14552,14552,아우디 S4,아우디,S4,S4,1330,2995,2011,0색,...,8000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14553,14553,14553,기아 스포티지R,기아,스포티지,스포티지R (10~13년),800,1995,2011,검정색,...,2500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14554,14554,14554,폭스바겐 티구안(1세대),폭스바겐,티구안,티구안 1세대,1030,2000,2014,흰색,...,4290.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14555,14555,14555,제네시스 EQ900,제네시스,제네시스,EQ900,3390,5038,2016,검정색,...,9000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14556,14556,14556,현대 에쿠스(신형),현대,에쿠스,뉴 에쿠스,1680,3778,2015,검정색,...,8000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df['감가상각률'].isnull().sum()

2404